### ISSUE TITLE
Product controller test has failed

### ISSUE THREAD

**Issue by alexbutirskiy** [RubySquad/shop_one#14]
Also one test was marked as panding. This test should be written or deleted.

**Comment by Sirchik** [comment]
In test @item is nill.
            post :create, product: {name: "Product 1", price: '10', count: '1'}
            response.should redirect_to(product_path(assigns(:@item)))

**Comment by alexbutirskiy** [comment]
Could you fix it?

**Comment by Sirchik** [comment]
It was fixed in brForTest. But we have four fail tests :)
