### ISSUE TITLE
Devise doesn't send mail on successful registrtion

### ISSUE THREAD

**Issue by alexbutirskiy** [RubySquad/shop_one#25]
2.2) Для получения локально отправленных писем **регистраци** и восстановления пароля используйте гем mailcatcher - он будет ловить письма и отображать их в удобном вебинтерфейсе на 1080 порту (гем добавлять в group: :development)

**Comment by phagoth** [comment]
Да, этот сценарий я забыл проверить вчера. Исправил. Пришлось лезть в миграцию.
