### ISSUE TITLE
Need to make authorization feature

### ISSUE THREAD

**Issue by phagoth** [RubySquad/shop_one#3]

**Comment by phagoth** [comment]
Almost done, but we need to find solution for storing user session

**Comment by phagoth** [comment]
All was rebuilt. Authorization is working now.
Users can:
- Register
- LogIn
- LogOut

Users temporary can't:
- Manage their own account

_Also we need to implement access by roles variants_

**Comment by phagoth** [comment]
Нужна помощь в нахождении бага, из-за которого при регистрации пользователя не происходит проверка на соответствие пароля и подтверждения пароля

**Comment by Sirchik** [comment]
Похоже это из-за то, что ты не добавил в пермит подтверждение пароля.

**Comment by phagoth** [comment]
Thanks a lot
