### ISSUE TITLE
Need to make catalogue controller&view

### ISSUE THREAD

**Issue by phagoth** [RubySquad/shop_one#4]

**Comment by alexbutirskiy** [comment]
Do it yourself

**Comment by phagoth** [comment]
## New features are available through the following actions:

### Action name: **index**

###### How to call: _/products/index (or just /products/)_
- displays all the records of the table **products**

### Action name: **show**

###### How to call: _/products/1 (for record with id=1)_
- displays a record of the table **products** with the specified id

### Action name: **new**

###### How to call: _/products/new_
- displays a form for new entry creation
- after pressing the Submit button automatically calls **create** action with the specified parameters 

### Action name: **edit**

###### How to call: _/products/1/edit (for record with id=1)_
- displays a form to edit an existing record with the specified id
- after pressing the Submit button automatically calls **update** action with the specified parameters 

### Action name: **destroy**

###### How to call: _need to send DELETE method to the /products/1 (for record with id=1)_
- destroys an existing record with the specified id from table
