### ISSUE TITLE
Need to define storage for user data

### ISSUE THREAD

**Issue by phagoth** [RubySquad/shop_one#5]
After user's login we must store somewhere his data (name, user_id, etc.).
What can it be? Does we need to define global variable?

**Comment by alexbutirskiy** [comment]
Bohdan has told that it should be done by cookie which stores a session token. Unfortunately I can say it but I can't explain. So let's solve this task in the simplest way: everybody can byu goods without any authorisation.

**Comment by phagoth** [comment]
Actually this problem usually solved by **Devise** gem. But in our case, for using this gem we need rebuild **User** model :confused:

**Comment by phagoth** [comment]
I'll read about session and cookies and then choose which suits best.
